# -*- coding: utf-8 -*-
"""
Created on Sun Jun 21 21:02:48 2020

@author: zhixia liu
"""

"""
Project Euler 2: Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

#%% naive

a=1
b=2
s=2

while b<4000000:
    b=b+a
    a=b-a
    if b%2 ==0:
        s+=b

print(s)