# -*- coding: utf-8 -*-
"""
Created on Fri Jun 26 16:58:54 2020

@author: zhixia liu
"""

"""
Project Euler 29: Distinct powers

Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

"""

#%% by hand

total = 99*99
square = len([4,9,25,36,49,100])*49
cubic = len([8,27])*(32+17)
quadro = len([16,81])*(49+9)
n32 = 48
n64 = 62
print(total-square-cubic-quadro-n32-n64)

#%% bf
s = []
for a in range(2,101):
    for b in range(2,101):
        s.append(a**b)
print(len(set(s)))

